    - name: send discord message when cpu usage is over 90%
      uri:
        url: "https://discord.com/api/webhooks/1199337699656618004/yoV2LbuKw2lW76tAIKlqjIeFXkS4B3kMQEXvUMyqxGh-Bcx6RApYdOvepEV6RO3QfpoX"
        method: POST
        body_format: json
        body: '{"content": "cpu usage on {{ ansible_hostname }} is above 90%!"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: cpu_usage.stdout[:-1]|int > 90  

    - name: send discord message when ram usage is over 90%
      uri:
        url: "https://discord.com/api/webhooks/1199337699656618004/yoV2LbuKw2lW76tAIKlqjIeFXkS4B3kMQEXvUMyqxGh-Bcx6RApYdOvepEV6RO3QfpoX"
        method: POST
        body_format: json
        body: '{"content": "ram usage on {{ ansible_hostname }} is above 90%!"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: ram_usage.stdout[:-1]|int > 90

    - name: send discord message when disk usage is over 90%
      uri:
        url: "https://discord.com/api/webhooks/1199337699656618004/yoV2LbuKw2lW76tAIKlqjIeFXkS4B3kMQEXvUMyqxGh-Bcx6RApYdOvepEV6RO3QfpoX"
        method: POST
        body_format: json
        body: '{"content": "disk usage on {{ ansible_hostname }} is above 90%!"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: disk_usage.stdout[:-1]|int > 90