---
- hosts: all
  become: yes
  tasks:
  
    - name: get hostname and ip
      set_fact:
        remote_hostname: "{{ ansible_hostname }}"
        remote_ip: "{{ ansible_default_ipv4.address }}"

    - name: create nrpe config file on local server
      copy:
        content: |
          define host{
            use         linux-server
            host_name   {{ ansible_hostname }}
            address     {{ ansible_default_ipv4.address }}
          }

          define service{
            use                     local-service
            host_name               {{ ansible_hostname }}
            service_description     PING
            check_command           check_ping!100.0,20%!500.0,60%
          }

          define service{
            use                     local-service
            host_name               {{ ansible_hostname }}
            service_description     Root Partition
            check_command           check_local_disk!20%!10%!/
          }

          define service{
            use                     local-service
            host_name               {{ ansible_hostname }}
            service_description     Current Users
            check_command           check_local_users!20!50
          }

          define service{
            use                     local-service
            host_name               {{ ansible_hostname }}
            service_description     Total Processes
            check_command           check_local_procs!250!400!RSZDT
          }

          define service{
            use                     local-service
            host_name               {{ ansible_hostname }}
            service_description     Current Load
            check_command           check_local_load!5.0,4.0,3.0!10.0,6.0,4.0
          }

          define service{
            use                     local-service
            host_name               {{ ansible_hostname }}
            service_description     Swap Usage
            check_command           check_local_swap!20%!10%
          }

          define service{
            use                     local-service
            host_name               {{ ansible_hostname }}
            service_description     SSH
            check_command           check_ssh
          }
        dest: /tmp/{{ ansible_hostname }}.cfg

    - name: copy nrpe config file to monitoring server
      ansible.builtin.shell: sshpass -p '12345' scp -r /tmp/{{ ansible_hostname }}.cfg root@192.168.1.58:/usr/local/nagios/etc/servers

    - name: restart nagios service
      ansible.builtin.shell: sshpass -p '12345' ssh root@192.168.1.58 sudo systemctl restart nagios.service