---
- hosts: all
  vars_files:
    - secure_vars.yml
  tasks:
    - name: clone standard lxc container
      community.general.proxmox:
        api_host: 192.168.1.10
        node: proxmox
        api_user: root@pam
        api_password: 19990317a
        clone: 1000
        storage: VM-Drives
        vmid: 111 #if specific vmid if needed
        hostname: test-ansible #modify to desire hostname
        
    - name: start standard lxc container
      community.general.proxmox:
        api_host: 192.168.1.10
        node: proxmox
        api_user: root@pam
        api_password: 19990317a
        vmid: 111 #if specific vmid if needed
        hostname: test-ansible #modify to desire hostname
        state: started
