---
- hosts: all
  vars_files:
    - secure_vars.yml
  tasks:
    - name: clone standard lxc container
      community.general.proxmox:
        api_host: "{{ host }}"
        node: "{{ node }}"
        api_user: "{{ user }}"
        api_password: "{{ password }}"
        clone: 1000
        storage: VM-Drives
        vmid: 111 #if specific vmid if needed
        hostname: test-ansible #modify to desired hostname
        
    - name: start standard lxc container
      community.general.proxmox:
        api_host: "{{ host }}"
        node: "{{ node }}"
        api_user: "{{ user }}"
        api_password: "{{ password }}"
        vmid: 111 #if specific vmid if needed
        hostname: test-ansible #modify to desired hostname
        state: started
