---
- hosts: all
  vars_files:
    - secure_vars.yml
  tasks:

    - name: clone standard lxc container
      community.general.proxmox:
        api_host: 192.168.1.10
        node: proxmox
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        clone: 1000
        storage: VM-Drives
        vmid: 110 #if specific vmid if needed
        hostname: test-disk #modify to desire hostname
        
    - name: start standard lxc container
      community.general.proxmox:
        api_host: 192.168.1.10
        node: proxmox
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        vmid: 110 #if specific vmid if needed
        hostname: test-disk #modify to desire hostname
        state: started
