---
- hosts: all 
  become: yes
  tasks:
    - name: update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes

    - name: update packages with dnf
      when: ansible_pkg_mgr == 'dnf'
      dnf:
        update_cache: yes

    - name: upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        state: present

    - name: upgrade packages with dnf
      when: ansible_pkg_mgr == 'dnf'
      dnf:
        state: present
